Migrate Test tests/functional/fuse_subdir/test_auth_allow_fqdn.py
gluster/redant pull request #1030
Opened 2021-09-05 13:39 UTC by Sheetalpamecha

[Migrate Test tests/functional/fuse_subdir/test_auth_allow_fqdn.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/fuse_subdir/test_auth_allow_fqdn.py)

Updates: #292 
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

2021-09-05 13:40 UTC, Sheetalpamecha commented
```
Results for fuse_subdir
Test nature : disruptive
TestName : test_auth_allow_fqdn
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:01:37       |      NA     |
|     rep     |     PASS    |        00:01:44       |      NA     |
|   dist-rep  |     PASS    |        00:01:51       |      NA     |
|     disp    |     PASS    |        00:01:47       |      NA     |
|  dist-disp  |     PASS    |        00:01:52       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   5   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 10 minutes 31 seconds
```

2021-09-06 05:23 UTC, nik-redhat requested changes

2021-09-06 05:23 UTC, nik-redhat commented on common/ops/gluster_ops/mount_ops.py
> +            return ret
What's the use of `excep` here?
We are by default passing `False` to `excep` param  in `execute_abstract_op_node`

2021-09-06 05:23 UTC, nik-redhat commented on tests/functional/fuse_subdir/test_auth_allow_fqdn.py
> +        cmd = (f"mount.glusterfs {self.server_list[0]}:/{subdir_mount2} \
I think the `unauthenticated_mount` function can be used here and below as well?

2021-09-07 04:37 UTC, Sheetalpamecha commented on common/ops/gluster_ops/mount_ops.py
> +            return ret
Yeah i was trying it out and changed it.

2021-09-07 04:37 UTC, Sheetalpamecha commented on tests/functional/fuse_subdir/test_auth_allow_fqdn.py
> +        cmd = (f"mount.glusterfs {self.server_list[0]}:/{subdir_mount2} \
No we cant use it, But I added a function in this TC only to avoid code redundancy

2021-09-07 06:19 UTC, nik-redhat commented on tests/functional/fuse_subdir/test_auth_allow_fqdn.py
> +    """
A terminate is needed as we have in [this TC](https://github.com/gluster/redant/blob/main/tests/functional/fuse_subdir/test_multisubdir_with_multiclient.py) in order to unmount the subdir mounted in the TC.

2021-09-07 10:58 UTC, Sheetalpamecha commented
```
Results for fuse_subdir
Test nature : disruptive
TestName : test_auth_allow_fqdn
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:01:37       |      NA     |
|     rep     |     PASS    |        00:01:35       |      NA     |
|   dist-rep  |     PASS    |        00:01:46       |      NA     |
|     disp    |     PASS    |        00:01:36       |      NA     |
|  dist-disp  |     PASS    |        00:01:45       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   5   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 09 minutes 50 seconds
```

2021-09-07 10:58 UTC, Sheetalpamecha commented on tests/functional/fuse_subdir/test_auth_allow_fqdn.py
> +    """
Done

2021-09-07 12:01 UTC, nik-redhat approved these changes

2021-09-07 12:01 UTC, merged