Migrate TC tests/functional/disperse/test_disperse_eager_lock.py
gluster/redant pull request #1031
Opened 2021-09-05 16:37 UTC by Sheetalpamecha

[Migrate TC tests/functional/disperse/test_disperse_eager_lock.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_disperse_eager_lock.py)

Updates: #292
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

2021-09-05 16:38 UTC, Sheetalpamecha commented
```
Results for Special
Test nature : nonDisruptive
TestName : vol_create_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     disp    |     PASS    |        00:00:27       |      NA     |
|  dist-disp  |     PASS    |        00:00:29       |      NA     |
+-------------+-------------+-----------------------+-------------+
TestName : vol_destroy_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     disp    |     PASS    |        00:00:55       |      NA     |
|  dist-disp  |     PASS    |        00:01:02       |      NA     |
+-------------+-------------+-----------------------+-------------+
Results for disperse
Test nature : nonDisruptive
TestName : test_disperse_eager_lock
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|  dist-disp  |     PASS    |        00:02:02       |      NA     |
|     disp    |     PASS    |        00:02:04       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   0   |
|         Non Disruptive Tests         |   3   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   6   |
|            Tests Skipped             |   0   |
|             Total Tests              |   3   |
|   Disruptive Tests Pass Percentage   |   0   |
| Non Disruptive Tests Pass Percentage | 100.0 |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 05 minutes 06 seconds
```

2021-09-06 04:42 UTC, srijan-sivakumar requested changes

2021-09-06 04:42 UTC, srijan-sivakumar commented on tests/functional/disperse/test_disperse_eager_lock.py
> +    def get_random_string(self, chars, str_len=4):
nit: `_get_random_string`.  Also, this method can be made static.

2021-09-06 04:45 UTC, Sheetalpamecha commented on tests/functional/disperse/test_disperse_eager_lock.py
> +    def get_random_string(self, chars, str_len=4):
okay, will do

2021-09-06 06:40 UTC, nik-redhat commented on tests/functional/disperse/test_disperse_eager_lock.py
> +                                "Eagerlock shouldn't result in failure")
We don't need this as we are not bypassing the exception check in the set_volume_option function itself. So, in case the set operation fails, the exception will be raised inside the function itself and we will never reach here.

2021-09-07 04:11 UTC, Sheetalpamecha commented on tests/functional/disperse/test_disperse_eager_lock.py
> +                                "Eagerlock shouldn't result in failure")
Done

2021-09-07 05:51 UTC, nik-redhat approved these changes

2021-09-07 05:52 UTC, merged