Migrated TC test_no_fresh_lookup_on_directory
gluster/redant pull request #1056
Opened 2021-09-08 13:08 UTC by nik-redhat

Migrated TC [test_no_fresh_lookup_on_directory](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_no_fresh_lookup_on_directory.py)

Updates: #292 
Signed-off-by: nik-redhat <nladha@redhat.com>

2021-09-08 13:10 UTC, nik-redhat commented
```
Results for disperse
Test nature : disruptive
TestName : test_no_fresh_lookup_on_directory
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|  dist-disp  |     PASS    |        00:00:35       |      NA     |
|   dist-rep  |     PASS    |        00:00:35       |      NA     |
|   dist-arb  |     PASS    |        00:00:37       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   3   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 02 minutes 02 seconds
✔ Tearing down successful.
```

2021-09-08 18:09 UTC, nik-redhat commented
```
Results for Special
Test nature : nonDisruptive
TestName : vol_create_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   dist-arb  |     PASS    |        00:00:10       |      NA     |
|   dist-rep  |     PASS    |        00:00:10       |      NA     |
|  dist-disp  |     PASS    |        00:00:08       |      NA     |
+-------------+-------------+-----------------------+-------------+
TestName : vol_destroy_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   dist-arb  |     PASS    |        00:00:16       |      NA     |
|   dist-rep  |     PASS    |        00:00:16       |      NA     |
|  dist-disp  |     PASS    |        00:00:08       |      NA     |
+-------------+-------------+-----------------------+-------------+
Results for disperse
Test nature : nonDisruptive
TestName : test_no_fresh_lookup_on_directory
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   dist-arb  |     PASS    |        00:00:47       |      NA     |
|   dist-rep  |     PASS    |        00:00:47       |      NA     |
|  dist-disp  |     PASS    |        00:00:34       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   0   |
|         Non Disruptive Tests         |   3   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   9   |
|            Tests Skipped             |   0   |
|             Total Tests              |   3   |
|   Disruptive Tests Pass Percentage   |   0   |
| Non Disruptive Tests Pass Percentage | 100.0 |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 02 minutes 20 seconds
✔ Tearing down successful.
```
Results for Special
Test nature : nonDisruptive
TestName : vol_create_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:00:07       |      NA     |
|     dist    |     PASS    |        00:00:08       |      NA     |
|     disp    |     PASS    |        00:00:08       |      NA     |
|   dist-rep  |     PASS    |        00:00:08       |      NA     |
|  dist-disp  |     PASS    |        00:00:09       |      NA     |
+-------------+-------------+-----------------------+-------------+
TestName : vol_destroy_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:00:09       |      NA     |
|     dist    |     PASS    |        00:00:08       |      NA     |
|     disp    |     PASS    |        00:00:10       |      NA     |
|   dist-rep  |     PASS    |        00:00:11       |      NA     |
|  dist-disp  |     PASS    |        00:00:09       |      NA     |
+-------------+-------------+-----------------------+-------------+
Results for fuse_subdir
Test nature : nonDisruptive
TestName : test_subdir_mount
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:00:29       |      NA     |
|     dist    |     PASS    |        00:00:29       |      NA     |
|     disp    |     PASS    |        00:00:35       |      NA     |
|   dist-rep  |     PASS    |        00:00:35       |      NA     |
|  dist-disp  |     PASS    |        00:00:29       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   0   |
|         Non Disruptive Tests         |   3   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   15  |
|            Tests Skipped             |   0   |
|             Total Tests              |   3   |
|   Disruptive Tests Pass Percentage   |   0   |
| Non Disruptive Tests Pass Percentage | 100.0 |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 02 minutes 44 seconds
✔ Tearing down successful.
```

2021-09-09 05:45 UTC, Sheetalpamecha requested changes

2021-09-09 05:45 UTC, Sheetalpamecha commented on tests/functional/disperse/test_no_fresh_lookup_on_directory.py
> +# nonDisruptive;dist-disp,dist-rep,dist-arb
Why you converted tc from Disruptive to nonDisruptive? 
As we are making changes in cluster by bringing bricks down

2021-09-09 05:49 UTC, nik-redhat commented on tests/functional/disperse/test_no_fresh_lookup_on_directory.py
> +# nonDisruptive;dist-disp,dist-rep,dist-arb
We are making changes at the volume level, not at the cluster level.

2021-09-09 06:16 UTC, Sheetalpamecha commented on tests/functional/disperse/test_no_fresh_lookup_on_directory.py
> +# nonDisruptive;dist-disp,dist-rep,dist-arb
okay

2021-09-09 06:17 UTC, Sheetalpamecha approved these changes

2021-09-09 06:17 UTC, merged