Migrated TC test_ec_version_healing_when_one_brick_down
gluster/redant pull request #1057
Opened 2021-09-08 13:48 UTC by nik-redhat

Migrated TC [test_ec_version_healing_when_one_brick_down](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_version_healing_when_one_brick_down.py)

Updates: #292
Signed-off-by: nik-redhat <nladha@redhat.com>

2021-09-08 16:24 UTC, nik-redhat commented
```
Results for disperse
Test nature : disruptive
TestName : test_ec_version_healing_when_one_brick_down
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     disp    |     PASS    |        00:00:54       |      NA     |
|  dist-disp  |     PASS    |        00:00:45       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   2   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 01 minutes 53 seconds
✔ Tearing down successful.
```

2021-09-08 17:42 UTC, nik-redhat commented
```
Results for Special
Test nature : nonDisruptive
TestName : vol_create_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     disp    |     PASS    |        00:00:10       |      NA     |
|  dist-disp  |     PASS    |        00:00:10       |      NA     |
+-------------+-------------+-----------------------+-------------+
TestName : vol_destroy_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|  dist-disp  |     PASS    |        00:00:09       |      NA     |
|     disp    |     PASS    |        00:00:06       |      NA     |
+-------------+-------------+-----------------------+-------------+
Results for disperse
Test nature : nonDisruptive
TestName : test_ec_version_healing_when_one_brick_down
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|  dist-disp  |     PASS    |        00:00:40       |      NA     |
|     disp    |     PASS    |        00:00:59       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   0   |
|         Non Disruptive Tests         |   3   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   6   |
|            Tests Skipped             |   0   |
|             Total Tests              |   3   |
|   Disruptive Tests Pass Percentage   |   0   |
| Non Disruptive Tests Pass Percentage | 100.0 |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 01 minutes 29 seconds
✔ Tearing down successful.
```

2021-09-09 05:32 UTC, Sheetalpamecha requested changes

2021-09-09 05:32 UTC, Sheetalpamecha commented on tests/functional/disperse/test_ec_version_healing_when_one_brick_down.py
> +# nonDisruptive;disp,dist-disp
Shouldn't this be disruptive?

2021-09-09 05:37 UTC, nik-redhat commented on tests/functional/disperse/test_ec_version_healing_when_one_brick_down.py
> +# nonDisruptive;disp,dist-disp
Why?
It is only bringing a brick down, so that will not cause any issue if ran as nonDiruptvie.

2021-09-09 06:10 UTC, Sheetalpamecha commented on tests/functional/disperse/test_ec_version_healing_when_one_brick_down.py
> +# nonDisruptive;disp,dist-disp
okay

2021-09-09 06:10 UTC, Sheetalpamecha approved these changes

2021-09-09 06:11 UTC, merged