Migrate TC test_wipe_out_directory_permissions.py
gluster/redant pull request #1094
Opened 2021-09-20 06:37 UTC by Sheetalpamecha

Migrate TC [test_wipe_out_directory_permissions.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_wipe_out_directory_permissions.py)

Updates: #292 
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

2021-09-20 06:37 UTC, Sheetalpamecha commented
```
Results for dht
Test nature : disruptive
TestName : test_wipe_out_directory_permissions
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:01:54       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 03 minutes 56 seconds

```

2021-09-20 13:37 UTC, nik-redhat requested changes

2021-09-20 13:37 UTC, nik-redhat commented on tests/functional/dht/test_wipe_out_directory_permissions.py
> +                raise Exception("Not able to get stat of the dir")
We don't seem to be validating the expected permissions here.

2021-09-24 05:42 UTC, Sheetalpamecha commented on tests/functional/dht/test_wipe_out_directory_permissions.py
> +                raise Exception("Not able to get stat of the dir")
Added the check. But there seems to be a bug here. Directory permissions changes on cd/ls operation on mountpoint without explicit changing from us. Tried it manually too and ran into this bug.

2021-09-24 06:38 UTC, nik-redhat commented on tests/functional/dht/test_wipe_out_directory_permissions.py
> +                raise Exception("Not able to get stat of the dir")
Ok, so did they have some other permission?

2021-09-24 06:39 UTC, Sheetalpamecha commented on tests/functional/dht/test_wipe_out_directory_permissions.py
> +                raise Exception("Not able to get stat of the dir")
No

2021-09-24 08:03 UTC, nik-redhat commented on tests/functional/dht/test_wipe_out_directory_permissions.py
> +                raise Exception("Not able to get stat of the dir")
Ok, it seems to be working on downstream code but not on upstream latest code.
Then, I think it is better to mark it as excluded with this justification.

2021-09-24 08:16 UTC, Sheetalpamecha commented on tests/functional/dht/test_wipe_out_directory_permissions.py
> +                raise Exception("Not able to get stat of the dir")
okay

2021-09-24 09:19 UTC, nik-redhat approved these changes

2021-09-24 09:19 UTC, merged