Migrate TC test_verify_permissions_on_root_dir_when_brick_down.py
gluster/redant pull request #1099
Opened 2021-09-20 11:46 UTC by Sheetalpamecha

Migrate TC [test_verify_permissions_on_root_dir_when_brick_down.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_verify_permissions_on_root_dir_when_brick_down.py)

Updates: #292
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

2021-09-20 11:46 UTC, Sheetalpamecha commented
```
Results for Special
Test nature : nonDisruptive
TestName : vol_create_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:00:24       |      NA     |
|   dist-rep  |     PASS    |        00:00:29       |      NA     |
|   dist-arb  |     PASS    |        00:01:04       |      NA     |
|  dist-disp  |     PASS    |        00:01:01       |      NA     |
+-------------+-------------+-----------------------+-------------+
TestName : vol_destroy_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:03:04       |      NA     |
|   dist-rep  |     PASS    |        00:03:09       |      NA     |
|   dist-arb  |     PASS    |        00:01:10       |      NA     |
|  dist-disp  |     PASS    |        00:01:50       |      NA     |
+-------------+-------------+-----------------------+-------------+
Results for dht
Test nature : nonDisruptive
TestName : test_verify_permissions_on_root_dir_when_brick_down
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   dist-rep  |     PASS    |        00:06:11       |      NA     |
|     dist    |     PASS    |        00:06:17       |      NA     |
|   dist-arb  |     PASS    |        00:03:17       |      NA     |
|  dist-disp  |     PASS    |        00:03:40       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   0   |
|         Non Disruptive Tests         |   3   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   12  |
|            Tests Skipped             |   0   |
|             Total Tests              |   3   |
|   Disruptive Tests Pass Percentage   |   0   |
| Non Disruptive Tests Pass Percentage | 100.0 |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 18 minutes 30 seconds
```

2021-09-20 13:32 UTC, nik-redhat requested changes
Let's add the terminate function to reset the permissions on the directory to 755.

2021-09-21 09:15 UTC, Sheetalpamecha commented
```
Results for Special
Test nature : nonDisruptive
TestName : vol_create_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:00:59       |      NA     |
|   dist-rep  |     PASS    |        00:01:02       |      NA     |
|   dist-arb  |     PASS    |        00:00:45       |      NA     |
|  dist-disp  |     PASS    |        00:00:36       |      NA     |
+-------------+-------------+-----------------------+-------------+
TestName : vol_destroy_test
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:01:29       |      NA     |
|   dist-rep  |     PASS    |        00:01:38       |      NA     |
|   dist-arb  |     PASS    |        00:01:35       |      NA     |
|  dist-disp  |     PASS    |        00:01:48       |      NA     |
+-------------+-------------+-----------------------+-------------+
Results for dht
Test nature : nonDisruptive
TestName : test_verify_permissions_on_root_dir_when_brick_down
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:02:53       |      NA     |
|   dist-rep  |     PASS    |        00:02:57       |      NA     |
|   dist-arb  |     PASS    |        00:03:27       |      NA     |
|  dist-disp  |     PASS    |        00:03:33       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   0   |
|         Non Disruptive Tests         |   3   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   12  |
|            Tests Skipped             |   0   |
|             Total Tests              |   3   |
|   Disruptive Tests Pass Percentage   |   0   |
| Non Disruptive Tests Pass Percentage | 100.0 |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 13 minutes 39 seconds
```

2021-09-21 09:16 UTC, Sheetalpamecha commented
> Let's add the terminate function to reset the permissions on the directory to 755.

Done

2021-09-21 09:31 UTC, nik-redhat approved these changes

2021-09-21 09:31 UTC, merged