Migrated TC test_open_file_migration
gluster/redant pull request #1132
Opened 2021-09-28 12:12 UTC by nik-redhat

Migrated TC [test_open_file_migration](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_open_file_migration.py)

Updates: #292 
Signed-off-by: nik-redhat <nladha@redhat.com>

2021-09-28 13:18 UTC, nik-redhat commented
```
Results for dht
Test nature : disruptive
TestName : test_open_file_migration
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:03:45       |      NA     |
|     rep     |     PASS    |        00:03:53       |      NA     |
|     arb     |     PASS    |        00:03:53       |      NA     |
|     disp    |     PASS    |        00:05:04       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   4   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 16 minutes 52 seconds
✔ Tearing down successful.
```

2021-09-29 08:39 UTC, Sheetalpamecha requested changes

2021-09-29 08:39 UTC, Sheetalpamecha commented on tests/functional/dht/test_open_file_migration.py
> +
a terminate function is required if the tc fails while expand or rebalance

2021-09-29 08:57 UTC, nik-redhat commented on tests/functional/dht/test_open_file_migration.py
> +
Done

2021-09-29 09:07 UTC, Sheetalpamecha approved these changes

2021-09-29 09:07 UTC, merged