Migrate TC test_rebalance_two_volumes.log
gluster/redant pull request #1146
Opened 2021-09-30 13:12 UTC by Sheetalpamecha

Migrate TC[ test_rebalance_two_volumes.log](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_two_volumes.py)

Updates: #292
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

2021-09-30 13:14 UTC, Sheetalpamecha commented
```
Results for dht
Test nature : disruptive
TestName : test_rebalance_two_volumes
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:04:27       |      NA     |
|   dist-rep  |     PASS    |        00:07:24       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   2   |
|            Tests Skipped             |   0   |
|             Tests Passed             |   2   |
|             Tests Failed             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 13 minutes 57 seconds
✔ Tearing down successful.
```

2021-09-30 13:34 UTC, nik-redhat requested changes

2021-09-30 13:34 UTC, nik-redhat commented on tests/functional/dht/test_rebalance_two_volumes.py
> +            self.redant.cleanup_volume(self.server_list, self.second_vol_name)
We can avoid this, as the terminate function will take care of it by default for disruptive TCs.

2021-09-30 13:34 UTC, nik-redhat commented on tests/functional/dht/test_rebalance_two_volumes.py
> +        self.redant.volume_mount(self.server_list[0], self.vol_name,
It should be second volume as well. `self.second_volname`

2021-09-30 16:58 UTC, Sheetalpamecha commented on tests/functional/dht/test_rebalance_two_volumes.py
> +        self.redant.volume_mount(self.server_list[0], self.vol_name,
done

2021-09-30 16:58 UTC, Sheetalpamecha commented on tests/functional/dht/test_rebalance_two_volumes.py
> +            self.redant.cleanup_volume(self.server_list, self.second_vol_name)
okay

2021-09-30 16:58 UTC, Sheetalpamecha commented
```
Results for dht
Test nature : disruptive
TestName : test_rebalance_two_volumes
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:13:03       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Tests Passed             |   1   |
|             Tests Failed             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 23 minutes 53 seconds
✔ Tearing down successful.
```

2021-10-01 08:49 UTC, nik-redhat approved these changes

2021-10-01 08:49 UTC, merged