Migrated TC test_remove_brick_while_rebalance_is_running.py
gluster/redant pull request #1157
Opened 2021-10-02 18:02 UTC by Sheetalpamecha

Migrated TC[ test_remove_brick_while_rebalance_is_running.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_remove_brick_while_rebalance_is_running.py)

Updates: #292
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

2021-10-02 18:02 UTC, Sheetalpamecha commented
```
Results for dht
Test nature : disruptive
TestName : test_remove_brick_while_rebalance_is_running
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:02:43       |      NA     |
|     rep     |     PASS    |        00:03:15       |      NA     |
|     disp    |     PASS    |        00:01:58       |      NA     |
|   dist-rep  |     PASS    |        00:06:45       |      NA     |
|  dist-disp  |     PASS    |        00:03:06       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   5   |
|            Tests Skipped             |   0   |
|             Tests Passed             |   5   |
|             Tests Failed             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 18 minutes 01 seconds
✔ Tearing down successful.
```

2021-10-04 05:59 UTC, nik-redhat requested changes

2021-10-04 05:59 UTC, nik-redhat commented on tests/functional/dht/test_remove_brick_while_rebalance_is_running.py
> +                if ret['msg']['opRet'] != 0:
It should be `'0'` we get a string value for opRet.

2021-10-04 05:59 UTC, nik-redhat commented on tests/functional/dht/test_remove_brick_while_rebalance_is_running.py
> +            if ret['msg']['opRet'] == 0:
Same as above

2021-10-04 15:04 UTC, Sheetalpamecha commented on tests/functional/dht/test_remove_brick_while_rebalance_is_running.py
> +            if ret['msg']['opRet'] == 0:
Done

2021-10-04 15:10 UTC, nik-redhat commented
Could you please add the results again, considering the type of check would have still passed in case the value was == 0?

2021-10-04 15:12 UTC, Sheetalpamecha commented
> Could you please add the results again, considering the type of check would have still passed in case the value was == 0?

Yes I intend to. Once shared machine is available I will run TCs

2021-10-04 19:21 UTC, Sheetalpamecha commented
```
Results for dht
Test nature : disruptive
TestName : test_remove_brick_while_rebalance_is_running
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:03:15       |      NA     |
|     rep     |     PASS    |        00:02:38       |      NA     |
|     disp    |     PASS    |        00:02:02       |      NA     |
|   dist-rep  |     PASS    |        00:07:16       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   4   |
|            Tests Skipped             |   0   |
|             Tests Passed             |   4   |
|             Tests Failed             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 18 minutes 33 seconds
✔ Tearing down successful.

```

2021-10-05 05:24 UTC, nik-redhat approved these changes

2021-10-05 05:24 UTC, merged