Doc: Update setup instructions
gluster/redant pull request #1207
Opened 2022-01-09 15:11 UTC by nik-redhat

Signed-off-by: nik-redhat <nladha@redhat.com>

### All Submissions:

**Description:**
Updated the README to have the pre-requisites for running redant TCs.
Updated the heal timeout in a TC.

2022-01-12 05:45 UTC, nik-redhat commented
```
Results for dht
Test nature : disruptive
TestName : test_file_creation
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|  dist-disp  |     PASS    |        00:00:59       |      NA     |
|   dist-arb  |     PASS    |        00:01:01       |      NA     |
|   dist-rep  |     PASS    |        00:00:58       |      NA     |
|     dist    |     PASS    |        00:00:40       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   4   |
|            Tests Skipped             |   0   |
|             Tests Passed             |   4   |
|             Tests Failed             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 04 minutes 05 seconds
✔ Tearing down successful.
```

2022-01-17 14:32 UTC, Sheetalpamecha requested changes

2022-01-17 14:32 UTC, Sheetalpamecha commented on README.md
> +  5. automake
We don't need make,gcc,autoconf,automake for redant.

2022-01-17 14:32 UTC, Sheetalpamecha commented on README.md
> +  8. numpy
numpy will be installed with requirements.txt

2022-01-17 14:32 UTC, Sheetalpamecha commented on README.md
> +  9. sh
Why we need particularly sh?

2022-01-17 15:01 UTC, nik-redhat commented on README.md
> +  5. automake
No, we need them for the `arequal` and the `crefi` installation.

2022-01-17 15:02 UTC, nik-redhat commented on README.md
> +  8. numpy
Yes, but only in the control node.
We need it on all the nodes for the `file_dir_ops` script to work correctly in one go.

2022-01-17 15:02 UTC, nik-redhat commented on README.md
> +  9. sh
For the `file_dir_ops` script.

2022-01-17 15:31 UTC, Sheetalpamecha approved these changes

2022-01-17 15:31 UTC, merged