Core: Fix vol type check in test list builder
gluster/redant pull request #1208
Opened 2022-01-10 10:36 UTC by nik-redhat

Signed-off-by: nik-redhat <nladha@redhat.com>

### All Submissions:

**Description:**
The condition to check for config was incorrect, it filtered out the "Genric" volumes as well.
Updated the code to use "OR" instead of "AND" for the check.

2022-01-10 11:02 UTC, nik-redhat commented
Generic TC:
```
Results for glusterd
Test nature : disruptive
TestName : test_brickmux_brick_process
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   Generic   |     PASS    |        00:01:40       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Tests Passed             |   1   |
|             Tests Failed             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 02 minutes 06 seconds
✔ Tearing down successful.
```

TC with 1 vol-type and that is not included in the config file:
```
(rvirt) [root@dhcp41-220 redant]# python3 core/redant_main.py -c ../config.yml -ll D -t tests/functional/glusterd/test_add_brick.py 
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

✔ Param Handling Success.
✔ Test List built
✔ Log dir creation successful.
✔ Environment setup successful.
Either no tests to run or the requested test is in exclude list.
✔ Tearing down successful.
```

2022-01-17 14:35 UTC, Sheetalpamecha requested changes

2022-01-17 14:35 UTC, Sheetalpamecha commented on tests/functional/dht/test_verify_permissions_on_root_dir_when_brick_down.py
>  from tests.nd_parent_test import NdParentTest
should be `from tests.d_parent_test import DParentTest`

2022-01-17 15:05 UTC, nik-redhat commented on tests/functional/dht/test_verify_permissions_on_root_dir_when_brick_down.py
>  from tests.nd_parent_test import NdParentTest
Done

2022-01-17 15:31 UTC, Sheetalpamecha approved these changes

2022-01-17 15:31 UTC, merged