Skip tests working only on upstream/RHGS accordingly
gluster/redant pull request #1209
Opened 2022-01-27 12:20 UTC by nik-redhat

Signed-off-by: nik-redhat <nladha@redhat.com>

### All Submissions:
**Description:**
The PR segregates tests that could run either on upstream/RHGS installation for glusterd, glusterfind components.

2022-01-27 12:35 UTC, nik-redhat commented
Incase of RHGS installation:
```
✔ Running test case : test_localtime_logging_and_opversion_negative_case-dist
ℹ test_localtime_logging_and_opversion_negative_case-dist SKIP
Results for glusterd
Test nature : disruptive
TestName : test_localtime_logging_and_opversion_negative_case
+-------------+-------------+-----------------------+----------------------------------------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) |                 Skip Reason                  |
+-------------+-------------+-----------------------+----------------------------------------------+
|     dist    |     SKIP    |        00:00:22       | The test case requires Upstream installation |
+-------------+-------------+-----------------------+----------------------------------------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   1   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   0   |
|            Tests Skipped             |   1   |
|             Tests Passed             |   0   |
|             Tests Failed             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   |   0   |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         |   0   |
+--------------------------------------+-------+
Total Time Taken : 00 hours 00 minutes 49 seconds
✔ Tearing down successful.
```

```
Results for glusterd
Test nature : nonDisruptive
TestName : test_default_ping_timer_and_epoll_thread_count
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   Generic   |     PASS    |        00:00:14       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   0   |
|         Non Disruptive Tests         |   1   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Tests Passed             |   1   |
|             Tests Failed             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   |   0   |
| Non Disruptive Tests Pass Percentage | 100.0 |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 00 minutes 41 seconds
✔ Tearing down successful.
```

2022-01-28 05:41 UTC, Sheetalpamecha requested changes

2022-01-28 05:41 UTC, Sheetalpamecha commented on tests/functional/glusterd/test_localtime_logging_and_opversion_negative_case.py
> +        """
Before setting up volume only, we should check type of installation.

2022-01-28 06:11 UTC, nik-redhat commented on tests/functional/glusterd/test_localtime_logging_and_opversion_negative_case.py
> +        """
Missed it.....done.

2022-01-28 06:20 UTC, Sheetalpamecha approved these changes

2022-01-28 06:20 UTC, merged