Migrated test_healed_and_heal_failed_command
gluster/redant pull request #811
Opened 2021-07-13 08:30 UTC by aujjwal-redhat

Migrated
[test_healed_and_heal_failed_command](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_healed_and_heal_failed_command.py)

Updates: #292

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-07-13 12:50 UTC, aujjwal-redhat commented
```sh

Results for afr
Test nature : disruptive
TestName : test_healed_and_heal_failed_command
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:02:18       |      NA     |
+-------------+-------------+-----------------------+-------------+
```

2021-07-13 14:29 UTC, nik-redhat requested changes

2021-07-13 14:29 UTC, nik-redhat commented on tests/functional/afr/test_healed_and_heal_failed_command.py
> +            raise Exception(f"{cmd} heal-failed should list 'Usage'")
You have missed the `healed_failed` part but added the check for them. Please rectify.

2021-07-13 14:37 UTC, aujjwal-redhat commented on tests/functional/afr/test_healed_and_heal_failed_command.py
> +            raise Exception(f"{cmd} heal-failed should list 'Usage'")
Ack.

2021-07-13 14:37 UTC, aujjwal-redhat commented on tests/functional/afr/test_healed_and_heal_failed_command.py
> +
Ack

2021-07-14 06:02 UTC, aujjwal-redhat commented
```sh

Results for afr
Test nature : disruptive
TestName : test_healed_and_heal_failed_command
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:02:20       |      NA     |
+-------------+-------------+-----------------------+-------------+
```

2021-07-14 06:06 UTC, nik-redhat approved these changes

2021-07-14 06:19 UTC, merged