Migrated test_readlink
gluster/redant pull request #825
Opened 2021-07-14 13:11 UTC by aujjwal-redhat

Migrated the [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_readlink.py)

Updates: #292

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-07-14 13:13 UTC, aujjwal-redhat commented
```sh
Results for afr
Test nature : nonDisruptive
TestName : test_readlink
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:00:36       |      NA     |
+-------------+-------------+-----------------------+-------------+
```

2021-07-14 13:17 UTC, aujjwal-redhat commented
```sh
{'mode': 'lrwxrwxrwx', 'user': 'root', 'group': 'root', 'permission': 777, 'fileType': 'symbolic link', 'atime': '1626267648.5383627', 'mtime': '1626267648.5428302', 'ctime': '1626267648.5428302', 'inode': 10895599865783613440, 'st_mode': 33188, 'st_ino': 10895599865783613440, 'st_dev': 40, 'st_nlink': 1, 'st_uid': 0, 'st_gid': 0, 'st_size': 12, 'st_atime': 1626267648, 'st_mtime': 1626267648, 'st_ctime': 1626267648}
```

This is how the stat dict looks

2021-07-14 14:03 UTC, srijan-sivakumar requested changes

2021-07-14 14:03 UTC, srijan-sivakumar commented on core/environ.py
> +                                                 io_script_dpath, node,
Also...The remove is currently being done every time...I think we can make this a configurable parameter..the reason why I'm thinking in this way is that even though it is not a bandwidth or resource intensive operation, we are still doing something again and again. Most of the times the script would not even be required to be modified or replaced. It is just in some rare moments we might need to replace the file_dir_ops.py. Maybe we can think of ways of how this can be done, though not a very big Pr blocking issue...just a food for thought..

2021-07-15 04:40 UTC, aujjwal-redhat commented on core/environ.py
> +                                                 io_script_dpath, node,
> Seems like a duplicate code...can't we combine the server and client list and run one single for loop...plus that'd reduce the code duplicity...

Ack

2021-07-15 04:54 UTC, aujjwal-redhat commented on core/environ.py
> +                                                 io_script_dpath, node,
> Also...The remove is currently being done every time...I think we can make this a configurable parameter..the reason why I'm thinking in this way is that even though it is not a bandwidth or resource intensive operation, we are still doing something again and again. Most of the times the script would not even be required to be modified or replaced. It is just in some rare moments we might need to replace the file_dir_ops.py. Maybe we can think of ways of how this can be done, though not a very big Pr blocking issue...just a food for thought..

We can make this configurable by two ways:

1. arg: add an argument to pass the file or list of files(considering in future if we have multiple files and we modify a few of them). But then again, people will have to notify explicitly that there was an update in the scripts and they must pass the script in the args to update with the new. This wouldn't be great in my opinion.
2. automatic check: We perform a script comparison every time to check if the two are same or not. In case of difference they will automatically replace it with the new. But then, again it will always compare in all the iterations which will consume some time.

The current procedure, removes and puts the new one which happens once every iteration.
In my opinion for now when we have just one script, and it takes time: `Remove time: 0.0014591217041015625`.

But yeah it is still consuming something.

Do lemme know any more ideas if you have.

2021-07-15 07:15 UTC, aujjwal-redhat commented on core/environ.py
> +                                                 io_script_dpath, node,
@srijan-sivakumar I have one more idea...
We can compare the last modified time of both the files on the redant repo and server tmp folder and if the last mod time of the redant repo is more than the tmp one in server then we can copy the file.

But then it will consume some time in getting the result from the server.

2021-07-15 11:54 UTC, srijan-sivakumar commented on core/environ.py
> +                                                 io_script_dpath, node,
Seeing the time I think we can ignore this...This is too small a time to even take into consideration.

2021-07-15 12:10 UTC, aujjwal-redhat commented
```sh

Results for afr
Test nature : nonDisruptive
TestName : test_readlink
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:00:34       |      NA     |
+-------------+-------------+-----------------------+-------------+
```

2021-07-15 13:33 UTC, srijan-sivakumar approved these changes

2021-07-15 13:33 UTC, merged

2021-07-21 10:00 UTC, nik-redhat commented on core/environ.py
> +            io_script_dpath)
Why are we are transferring the files to all the machines? We need this file only on client machines, right?

2021-07-21 10:07 UTC, aujjwal-redhat commented on tests/functional/afr/test_readlink.py
> +                                f"{stat_dict['filetype']}")
@nik-redhat as we can see in this part of the code we need file stat info from all the brick nodes. Hence we need to have the file_dir_ops script in the servers as well.