Migrated test_replica_eager_lock
gluster/redant pull request #832
Opened 2021-07-16 05:30 UTC by aujjwal-redhat

Migrated
[test_replica_eager_lock](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_replica_eager_lock.py)

Updates: #292

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-07-16 11:10 UTC, aujjwal-redhat commented
This tc is complete.
Issue :
Sometimes the last part of the tc `gluster v profile test_replica_eager_lock-rep info | grep OPENDIR | awk '{print$8}`

```log
[2021-07-16 16:35:14,898] INFO  - Running gluster v profile test_replica_eager_lock-rep info | grep OPENDIR | awk '{print$8}' on 10.70.43.115
[2021-07-16 16:35:15,193] DEBUG  - {'msg': ['1\n', '5\n'], 'Flag': True, 'node': '10.70.43.115', 'cmd': "gluster v profile test_replica_eager_lock-rep info | grep OPENDIR | awk '{print$8}'", 'error_code': 0}

```
While sometimes:
```log
[2021-07-16 16:35:55,817] INFO  - Running gluster v profile test_replica_eager_lock-dist-rep info | grep OPENDIR | awk '{print$8}' on 10.70.43.115
[2021-07-16 16:35:56,085] DEBUG  - {'msg': ['1\n', '1\n'], 'Flag': True, 'node': '10.70.43.115', 'cmd': "gluster v profile test_replica_eager_lock-dist-rep info | grep OPENDIR | awk '{print$8}'", 'error_code': 0}
```

Because of this sometimes tc fails.

2021-07-28 04:31 UTC, aujjwal-redhat commented
```sh

Results for afr
Test nature : disruptive
TestName : test_replica_eager_lock
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:00:38       |      NA     |
|   dist-rep  |     PASS    |        00:00:46       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 01 minutes 34 seconds
```

2021-07-28 08:40 UTC, srijan-sivakumar requested changes

2021-07-28 08:40 UTC, srijan-sivakumar commented on tests/functional/afr/test_replica_eager_lock.py
> +        for i in range(20):
seeing that i isn't even used, we can replace `i` with `_`.

2021-07-28 08:52 UTC, aujjwal-redhat commented on tests/functional/afr/test_replica_eager_lock.py
> +        for i in range(20):
ack

2021-07-28 08:57 UTC, srijan-sivakumar approved these changes

2021-07-28 09:01 UTC, merged