Migrated test_heal_info_while_accessing_file
gluster/redant pull request #843
Opened 2021-07-19 12:31 UTC by aujjwal-redhat

Migrated [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/heal/test_heal_info_while_accessing_file.py)

Updates: #292

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-07-19 12:34 UTC, aujjwal-redhat commented
```sh
✔ test_heal_info_while_accessing_file-dist-rep Succeeded
Results for heal
Test nature : disruptive
TestName : test_heal_info_while_accessing_file
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   dist-rep  |     PASS    |        00:07:27       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 07 minutes 40 seconds
```

2021-07-19 13:08 UTC, srijan-sivakumar requested changes

2021-07-19 13:08 UTC, srijan-sivakumar commented on tests/functional/afr/heal/test_heal_info_while_accessing_file.py
> +        self.counter = 1
Are we using this variable anywhere ? I don't seem to find it anywhere...

2021-07-19 13:13 UTC, aujjwal-redhat commented on tests/functional/afr/heal/test_heal_info_while_accessing_file.py
> +        self.counter = 1
True. Will reomve that. It's no where used in tc

2021-07-20 04:01 UTC, srijan-sivakumar approved these changes

2021-07-20 04:02 UTC, merged