[Doc] Adding Snap ops markdown
gluster/redant pull request #846
Opened 2021-07-19 14:43 UTC by srijan-sivakumar

Added snap ops markdown doc.

Fixes: #839

Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

### All Submissions:

Desciption:

(If it closes the issue)
Fixes: #
(If it just updates the Issue)
Updates: #

2021-07-21 04:54 UTC, aujjwal-redhat requested changes

2021-07-21 04:54 UTC, aujjwal-redhat commented on docs/BP/Ops/snap_ops.md
> +
It is not able to display in correct format.

Preview:

![Screenshot from 2021-07-21 10-21-50](https://user-images.githubusercontent.com/77244483/126432969-44507f7b-4813-4cbe-8a6a-f80acc5adb17.png)

2021-07-21 04:54 UTC, aujjwal-redhat commented on docs/BP/Ops/snap_ops.md
> +
Same is the case in the ones below as well.

2021-07-22 04:14 UTC, srijan-sivakumar commented on docs/BP/Ops/snap_ops.md
> +
I think it is not working in markdown. I just checked across the docs. The example is sticking out...This means we might need to also clear out from other docs.

2021-07-22 06:12 UTC, srijan-sivakumar commented on docs/BP/Ops/snap_ops.md
> +
@aujjwal-redhat I think we can take this in for now. We need to decide whether we are going to live with this type of documentation of shifting to readthedocs or github wiki in the coming days. Till then, I think this won't cause any confusion.

2021-07-22 06:21 UTC, aujjwal-redhat commented on docs/BP/Ops/snap_ops.md
> +
We can remove the *```python* completely then else anyone will get confused on seeing the examples part. Just a suggestion else we can keep it as it is.

2021-07-22 06:26 UTC, nik-redhat commented on docs/BP/Ops/snap_ops.md
> +
Hmm, then that can be made but not an urgent requirement I would say.

2021-07-22 06:28 UTC, aujjwal-redhat commented on docs/BP/Ops/snap_ops.md
> +
Yeah.

2021-07-22 06:29 UTC, aujjwal-redhat approved these changes

2021-07-22 06:30 UTC, merged