[Doc] Adding environ method details.
gluster/redant pull request #847
Opened 2021-07-20 05:21 UTC by srijan-sivakumar

Fixes: #437

Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

2021-07-21 04:56 UTC, aujjwal-redhat requested changes

2021-07-21 04:56 UTC, aujjwal-redhat commented on docs/BP/Core/environ.md
> +
Preview:
![Screenshot from 2021-07-21 10-25-45](https://user-images.githubusercontent.com/77244483/126433121-3f52544c-258b-42e5-8338-3c8751b70a33.png)

2021-07-22 06:22 UTC, srijan-sivakumar commented on docs/BP/Core/environ.md
> +
@aujjwal-redhat same as that of snap ops doc...we can live with this for now. We can modify the example section or maybe just see how to use both the \<br\> as well as the code annotation together when shifting

2021-07-22 06:23 UTC, nik-redhat approved these changes
Let's take this change in, as the issue "``" needs a complete repo wide change.

2021-07-22 06:27 UTC, aujjwal-redhat approved these changes

2021-07-22 06:30 UTC, merged