Migrated test_metadata_self_heal_on_open_fd
gluster/redant pull request #858
Opened 2021-07-22 12:09 UTC by aujjwal-redhat

Migrated
[test_metadata_self_heal_on_open_fd](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/test_metadata_self_heal_on_open_fd.py)

Updates: #292

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

2021-07-26 11:03 UTC, aujjwal-redhat commented
```sh

Results for arbiter
Test nature : disruptive
TestName : test_metadata_self_heal_on_open_fd
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:00:58       |      NA     |
|   dist-rep  |     PASS    |        00:01:05       |      NA     |
|     arb     |     PASS    |        00:01:00       |      NA     |
|   dist-arb  |     PASS    |        00:01:09       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 04 minutes 25 seconds
✔ Tearing down successful.
```

2021-07-26 11:11 UTC, aujjwal-redhat commented
If we check the arequal checksum total  of mountpoint  and bricks it is  'Total           : 8686b71de10aeeb9\n'] and 'Total           : 2e00\n' respectively.

```log
[2021-07-26 15:23:14,090] INFO  - arequal-checksum of mount 10.70.43.23:/mnt/test_metadata_self_heal_on_open_fd-rep/
[2021-07-26 15:23:14,099] INFO  - arequal-checksum of mount 10.70.41.159:/mnt/test_metadata_self_heal_on_open_fd-rep/
[2021-07-26 15:23:15,107] DEBUG  - {'msg': ['\n', 'Entry counts\n', 'Regular files   : 1\n', 'Directories     : 1\n', 'Symbolic links  : 0\n', 'Other           : 0\n', 'Total           : 2\n', '\n', 'Metadata checksums\n', 'Regular files   : 7fbf773e6\n', 'Directories     : 24d74c\n', 'Symbolic links  : 3e9\n', 'Other           : 3e9\n', '\n', 'Checksums\n', 'Regular files   : 39f51e508eb15b6cda1fc02b1ba08d8f\n', 'Directories     : 656c6966741b385a\n', 'Symbolic links  : 0\n', 'Other           : 0\n', 'Total           : 8686b71de10aeeb9\n'], 'Flag': True, 'node': '10.70.43.23', 'cmd': 'arequal-checksum /mnt/test_metadata_self_heal_on_open_fd-rep/', 'error_code': 0}
[2021-07-26 15:23:15,107] DEBUG  - {'msg': ['\n', 'Entry counts\n', 'Regular files   : 1\n', 'Directories     : 1\n', 'Symbolic links  : 0\n', 'Other           : 0\n', 'Total           : 2\n', '\n', 'Metadata checksums\n', 'Regular files   : 7fbf773e6\n', 'Directories     : 24d74c\n', 'Symbolic links  : 3e9\n', 'Other           : 3e9\n', '\n', 'Checksums\n', 'Regular files   : 39f51e508eb15b6cda1fc02b1ba08d8f\n', 'Directories     : 656c6966741b385a\n', 'Symbolic links  : 0\n', 'Other           : 0\n', 'Total           : 8686b71de10aeeb9\n'], 'Flag': True, 'node': '10.70.41.159', 'cmd': 'arequal-checksum /mnt/test_metadata_self_heal_on_open_fd-rep/', 'error_code': 0}
[2021-07-26 15:23:15,108] INFO  - Running gluster volume info test_metadata_self_heal_on_open_fd-rep --xml on 10.70.43.74
[2021-07-26 15:23:15,318] DEBUG  - {'msg': {'opRet': '0', 'opErrno': '0', 'opErrstr': None, 'volInfo': {'volumes': {'volume': {'name': 'test_metadata_self_heal_on_open_fd-rep', 'id': 'dbca9eef-bd2e-45fd-8bcf-9a3ebef25643', 'status': '1', 'statusStr': 'Started', 'snapshotCount': '0', 'brickCount': '3', 'distCount': '1', 'replicaCount': '3', 'arbiterCount': '0', 'disperseCount': '0', 'redundancyCount': '0', 'type': '2', 'typeStr': 'Replicate', 'transport': '0', 'bricks': {'brick': [{'@uuid': 'adf863d7-9a2a-45c3-86a9-4f520c7e7092', 'name': '10.70.43.74:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-0', 'hostUuid': 'adf863d7-9a2a-45c3-86a9-4f520c7e7092', 'isArbiter': '0', '#text': '10.70.43.74:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-0'}, {'@uuid': '0bd0d62f-6f95-477f-9106-cd1c620def21', 'name': '10.70.43.115:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-1', 'hostUuid': '0bd0d62f-6f95-477f-9106-cd1c620def21', 'isArbiter': '0', '#text': '10.70.43.115:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-1'}, {'@uuid': '46b98e38-da19-423a-a055-76365c5308eb', 'name': '10.70.41.159:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-2', 'hostUuid': '46b98e38-da19-423a-a055-76365c5308eb', 'isArbiter': '0', '#text': '10.70.41.159:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-2'}]}, 'optCount': '5', 'options': {'option': [{'name': 'cluster.granular-entry-heal', 'value': 'on'}, {'name': 'storage.fips-mode-rchecksum', 'value': 'on'}, {'name': 'transport.address-family', 'value': 'inet'}, {'name': 'nfs.disable', 'value': 'on'}, {'name': 'performance.client-io-threads', 'value': 'off'}]}}, 'count': '1'}}}, 'Flag': True, 'node': '10.70.43.74', 'cmd': 'gluster volume info test_metadata_self_heal_on_open_fd-rep --xml', 'error_code': 0}
[2021-07-26 15:23:15,320] INFO  - Running gluster volume info test_metadata_self_heal_on_open_fd-rep --xml on 10.70.43.74
[2021-07-26 15:23:15,573] DEBUG  - {'msg': {'opRet': '0', 'opErrno': '0', 'opErrstr': None, 'volInfo': {'volumes': {'volume': {'name': 'test_metadata_self_heal_on_open_fd-rep', 'id': 'dbca9eef-bd2e-45fd-8bcf-9a3ebef25643', 'status': '1', 'statusStr': 'Started', 'snapshotCount': '0', 'brickCount': '3', 'distCount': '1', 'replicaCount': '3', 'arbiterCount': '0', 'disperseCount': '0', 'redundancyCount': '0', 'type': '2', 'typeStr': 'Replicate', 'transport': '0', 'bricks': {'brick': [{'@uuid': 'adf863d7-9a2a-45c3-86a9-4f520c7e7092', 'name': '10.70.43.74:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-0', 'hostUuid': 'adf863d7-9a2a-45c3-86a9-4f520c7e7092', 'isArbiter': '0', '#text': '10.70.43.74:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-0'}, {'@uuid': '0bd0d62f-6f95-477f-9106-cd1c620def21', 'name': '10.70.43.115:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-1', 'hostUuid': '0bd0d62f-6f95-477f-9106-cd1c620def21', 'isArbiter': '0', '#text': '10.70.43.115:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-1'}, {'@uuid': '46b98e38-da19-423a-a055-76365c5308eb', 'name': '10.70.41.159:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-2', 'hostUuid': '46b98e38-da19-423a-a055-76365c5308eb', 'isArbiter': '0', '#text': '10.70.41.159:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-2'}]}, 'optCount': '5', 'options': {'option': [{'name': 'cluster.granular-entry-heal', 'value': 'on'}, {'name': 'storage.fips-mode-rchecksum', 'value': 'on'}, {'name': 'transport.address-family', 'value': 'inet'}, {'name': 'nfs.disable', 'value': 'on'}, {'name': 'performance.client-io-threads', 'value': 'off'}]}}, 'count': '1'}}}, 'Flag': True, 'node': '10.70.43.74', 'cmd': 'gluster volume info test_metadata_self_heal_on_open_fd-rep --xml', 'error_code': 0}
[2021-07-26 15:23:15,574] INFO  - Running arequal-checksum /glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-0/.glusterfs/landfill on 10.70.43.74
[2021-07-26 15:23:15,604] DEBUG  - {'msg': ['\n', 'Entry counts\n', 'Regular files   : 0\n', 'Directories     : 1\n', 'Symbolic links  : 0\n', 'Other           : 0\n', 'Total           : 1\n', '\n', 'Metadata checksums\n', 'Regular files   : 3e9\n', 'Directories     : 24d74c\n', 'Symbolic links  : 3e9\n', 'Other           : 3e9\n', '\n', 'Checksums\n', 'Regular files   : 00\n', 'Directories     : 2e00\n', 'Symbolic links  : 0\n', 'Other           : 0\n', 'Total           : 2e00\n'], 'Flag': True, 'node': '10.70.43.74', 'cmd': 'arequal-checksum /glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-0/.glusterfs/landfill', 'error_code': 0}
[2021-07-26 15:23:15,605] INFO  - Successfully calculated arequal for brick 10.70.43.74:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-0
[2021-07-26 15:23:15,606] INFO  - Running arequal-checksum /glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-1/.glusterfs/landfill on 10.70.43.115
[2021-07-26 15:23:15,639] DEBUG  - {'msg': ['\n', 'Entry counts\n', 'Regular files   : 0\n', 'Directories     : 1\n', 'Symbolic links  : 0\n', 'Other           : 0\n', 'Total           : 1\n', '\n', 'Metadata checksums\n', 'Regular files   : 3e9\n', 'Directories     : 24d74c\n', 'Symbolic links  : 3e9\n', 'Other           : 3e9\n', '\n', 'Checksums\n', 'Regular files   : 00\n', 'Directories     : 2e00\n', 'Symbolic links  : 0\n', 'Other           : 0\n', 'Total           : 2e00\n'], 'Flag': True, 'node': '10.70.43.115', 'cmd': 'arequal-checksum /glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-1/.glusterfs/landfill', 'error_code': 0}
[2021-07-26 15:23:15,640] INFO  - Successfully calculated arequal for brick 10.70.43.115:/glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-1
[2021-07-26 15:23:15,640] INFO  - Running arequal-checksum /glusterfs/brick/test_metadata_self_heal_on_open_fd-rep-2/.glusterfs/landfill on 10.70.41.159
[2021-07-26 15:23:15,671] DEBUG  - {'msg': ['\n', 'Entry counts\n', 'Regular files   : 0\n', 'Directories     : 1\n', 'Symbolic links  : 0\n', 'Other           : 0\n', 'Total           : 1\n', '\n', 'Metadata checksums\n', 'Regular files   : 3e9\n', 'Directories     : 24d74c\n', 'Symbolic links  : 3e9\n', 'Other           : 3e9\n', '\n', 'Checksums\n', 'Regular  [...]

2021-07-26 11:50 UTC, nik-redhat requested changes
Also, do try the `arequal-checksum` for the complete path, both for bricks and mountpoint i.e, for bricks it will be `only .glusterfs` and for mountpoint it will be the mount directory. Let's see what results we get for that.

2021-07-26 11:50 UTC, nik-redhat commented on common/ops/support_ops/io_ops.py
> +                bricks_list = 'gluster.blr.cluster.com:/bricks/brick1/vol'
Either remove this or change it to something simple like `[brick1, brick2]`

2021-07-26 11:50 UTC, nik-redhat commented on common/ops/support_ops/io_ops.py
> +        return (return_code, arequal_list)
Simply returning the list would do, if anyways the list has `None` as value the validation of the arequal being same will fail.

2021-07-26 11:50 UTC, nik-redhat commented on tests/functional/arbiter/test_metadata_self_heal_on_open_fd.py
> +        self.mounts = redant.es.get_mnt_pts_dict_in_list(self.vol_name)
We are running the IO only on 1 client, then why fetch the complete client,mount list. Simply create a dict like:
```
mount_dict = {
    'client': self.client_list[0],
    'moountpath': self.mountpoint
}
```
This will do as well.

2021-07-26 12:21 UTC, aujjwal-redhat commented on common/ops/support_ops/io_ops.py
> +                bricks_list = 'gluster.blr.cluster.com:/bricks/brick1/vol'
Ack

2021-07-26 12:21 UTC, aujjwal-redhat commented on common/ops/support_ops/io_ops.py
> +        return (return_code, arequal_list)
Ack

2021-07-26 12:23 UTC, aujjwal-redhat commented on tests/functional/arbiter/test_metadata_self_heal_on_open_fd.py
> +        self.mounts = redant.es.get_mnt_pts_dict_in_list(self.vol_name)
Ack

2021-07-27 06:16 UTC, aujjwal-redhat commented
```sh

Results for arbiter
Test nature : disruptive
TestName : test_metadata_self_heal_on_open_fd
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:01:38       |      NA     |
|   dist-rep  |     PASS    |        00:01:39       |      NA     |
|     arb     |     PASS    |        00:01:34       |      NA     |
|   dist-arb  |     PASS    |        00:01:38       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 06 minutes 44 seconds
```

2021-07-27 06:30 UTC, srijan-sivakumar approved these changes

2021-07-27 06:32 UTC, merged