Migrated TC test_brickcases
gluster/redant pull request #888
Opened 2021-07-27 09:16 UTC by nik-redhat

Migrated TC [test_brickcases](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/brick_cases/test_brickcases.py)

Updates: #292 
Signed-off-by: nik-redhat <nladha@redhat.com>

2021-07-27 13:02 UTC, nik-redhat commented
```
Results for brick_cases
Test nature : disruptive
TestName : test_brickcases
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   Generic   |     PASS    |        00:02:25       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 02 minutes 36 seconds
✔ Tearing down successful.
```

2021-07-27 13:22 UTC, srijan-sivakumar requested changes

2021-07-27 13:22 UTC, srijan-sivakumar commented on common/ops/gluster_ops/brick_ops.py
> +                        unused_servers.remove(server)
This can lead to some undefined behaviour...or atleast strange behavior. Lists in python are tricky...I'd suggest you try running the code

```python
list_val = [1, 2, 3, 4]
for val in list_val:
    print(val, list_val)
    list_val.remove(val)
```
Try running the above code. You'd find the loop not running as we'd expect in C.

The best way here would be to use a separate variables for iteration in for loop and removal altogether, that too obtained by a deepcopy of unused_servers

2021-07-27 13:29 UTC, srijan-sivakumar commented on common/ops/gluster_ops/brick_ops.py
> +                        unused_servers.remove(server)
For reference to how things work for python list during iteration -> [Link](https://blog.finxter.com/how-to-remove-items-from-a-list-while-iterating/)

2021-07-27 13:35 UTC, nik-redhat commented on common/ops/gluster_ops/brick_ops.py
> +                        unused_servers.remove(server)
Interesting issue, will update the code.

2021-07-27 13:54 UTC, nik-redhat commented
```
Results for brick_cases
Test nature : disruptive
TestName : test_brickcases
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   Generic   |     PASS    |        00:02:36       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 02 minutes 49 seconds
✔ Tearing down successful.
```

2021-07-27 14:22 UTC, srijan-sivakumar commented on common/ops/gluster_ops/brick_ops.py
> +            server_iter += 1
I'm not getting this logic..so basically, we are trying to prevent the new bricks from being added into the node that was the contained the last brick. And to prevent that we are increasing the server_iter by 1. But herein we are just comparing if that last node was the very first server in the server_list. What if say we have 3 servers and we have say 2, 2, 1. The last brick being in server 2. In this scenario, we'd be checking if last_node is the very first server in server_list. With it not being the last_node, we will add a new brick in server 1 itself. even though we should have say started with server 3 ( as it has lesser number of bricks ).

Just a thought...let me know if there is some other reasoning which I might be missing here.

2021-07-27 14:24 UTC, srijan-sivakumar commented on common/ops/gluster_ops/brick_ops.py
> +            server_iter += 1
Maybe the patch is about considering unused servers rather than optimizing with respect to brick weights ( i.e. number of bricks per server )

2021-07-27 14:49 UTC, nik-redhat commented on common/ops/gluster_ops/brick_ops.py
> +            server_iter += 1
> Maybe the patch is about considering unused servers rather than optimizing with respect to brick weights ( i.e. number of bricks per server )

Yes.....the scenario is that if we are creating bricks using fewer servers and have more servers left to consider while creating new bricks we should use that.
The above-mentioned scenario is not considered in this patch but can be done in a separate patch. Though, I don't have a logic yet on how to prevent all possible scenarios.

2021-07-28 08:21 UTC, srijan-sivakumar commented on common/ops/gluster_ops/brick_ops.py
> +            server_iter += 1
Cool. If possible, could you create a md inside RP for this change in brick ops. I feel we should start getting the design considerations into the RP directory so that if someone new wants to take things ahead, they can easily understand by glancing the doc once.

2021-07-28 08:22 UTC, srijan-sivakumar commented on common/ops/gluster_ops/brick_ops.py
> +            server_iter += 1
we can also take that as a separate issue for design updation and send separate set of patches to address that. Not blocking this PR for that updation..

2021-07-28 08:44 UTC, srijan-sivakumar approved these changes

2021-07-28 08:57 UTC, merged