Migrated TC test_afr_self_heal_add_brick_rebalance.py
gluster/redant pull request #923
Opened 2021-08-03 12:32 UTC by Sheetalpamecha

1. Create a replicated/distributed-replicate volume and mount it
2. Start IO from the clients
3. Bring down a brick from the subvol and validate it is offline
4. Bring back the brick online and wait for heal to complete
5. Once the heal is completed, expand the volume.
6. Trigger rebalance and wait for rebalance to complete
7. Validate IO, no errors during the steps performed from step 2
8. Check arequal of the subvol and all the brick in the same subvol
should have same checksum

Note: This tests is cleary for replicated volume types.

Change-Id: I2286e75cbee4f22a0ed14d6c320a4496dc3c3905
Signed-off-by: Bala Konda Reddy M <bala12352@gmail.com>

* Migrated TC test_afr_self_heal_add_brick_rebalance.py

Updates: #292
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

2021-08-03 13:10 UTC, srijan-sivakumar commented
@Sheetalpamecha can you attach the output.

2021-08-03 13:11 UTC, nik-redhat requested changes
In the commit-msg we can ignore the commit-msg of the old commit, and can simply shorten it to the TC name migrated, hyperlinked to the glusto-test repo link for the TC.

2021-08-03 13:11 UTC, nik-redhat commented on tests/functional/afr/heal/test_afr_self_heal_add_brick_rebalance.py
> +            raise Exception("IO failed on some of the clients")
I think the validation is not needed here, as we are doing it in the later part of the TC.

2021-08-03 13:11 UTC, nik-redhat commented on tests/functional/afr/heal/test_afr_self_heal_add_brick_rebalance.py
> +        self.io_validation_complete = True
We need to define this variable with `false` at the beginning of the TC, and also add a `terminate` function with `wait_for_io_to_complete` to validate the IO in case the TC fails before reaching here.

2021-08-03 13:11 UTC, nik-redhat commented on tests/functional/afr/heal/test_afr_self_heal_add_brick_rebalance.py
> +        self.all_mounts_procs *= 0
nit: Not needed

2021-08-03 13:11 UTC, nik-redhat commented on tests/functional/afr/heal/test_afr_self_heal_add_brick_rebalance.py
> +"""
nit: Add a description for the TC, something like what the TC does.

2021-08-03 16:00 UTC, Sheetalpamecha commented
Results for heal
Test nature : nonDisruptive
TestName : test_afr_self_heal_add_brick_rebalance
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:03:02       |      NA     |
|     arb     |     PASS    |        00:03:05       |      NA     |
|   dist-rep  |     PASS    |        00:03:20       |      NA     |
|   dist-arb  |     PASS    |        00:03:36       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   0   |
|         Non Disruptive Tests         |   3   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   3   |
|            Tests Skipped             |   0   |
|             Total Tests              |   3   |
|   Disruptive Tests Pass Percentage   |   0   |
| Non Disruptive Tests Pass Percentage | 100.0 |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 08 minutes 48 seconds
✔ Tearing down successful.

2021-08-03 16:29 UTC, srijan-sivakumar commented on tests/functional/afr/heal/test_afr_self_heal_add_brick_rebalance.py
> +        self.io_validation_complete = True
You can refer this [test](https://github.com/gluster/redant/blob/9b91ef2b21041279b0c73ba0b4522816edba2ca4/tests/functional/glusterd/test_profile_simultaneously_on_different_nodes.py#L31) for sample implementation of terminate and wait_for_io completion.

2021-08-03 16:37 UTC, srijan-sivakumar commented on tests/functional/afr/heal/test_afr_self_heal_add_brick_rebalance.py
> +            raise Exception("IO failed on some of the clients")
I think the nomenclature is to blame here. validation from redant POV will wait till the async process ends but our test case requires that the IO keep on happening on the background. Now if we still want to check if the async process is running, we can use the method, [check_async_command_status](https://github.com/gluster/redant/blob/9b91ef2b21041279b0c73ba0b4522816edba2ca4/common/rexe.py#L179) and as Nikhil mentioned the validation has to be done after the expansion and rebalance has been done.

2021-08-03 17:06 UTC, Sheetalpamecha commented on tests/functional/afr/heal/test_afr_self_heal_add_brick_rebalance.py
> +        self.io_validation_complete = True
Yes Thanks for the pointer Srijan

2021-08-03 17:11 UTC, nik-redhat commented on tests/functional/afr/heal/test_afr_self_heal_add_brick_rebalance.py
> +
We need to set the `io_validation_complete` to `False` here as the IO is still going on, and if the TC fails midway, we need to complete the IO before moving to cleanup.

2021-08-03 17:12 UTC, nik-redhat commented
Also,  do add the test results after the latest update.

2021-08-03 17:18 UTC, Sheetalpamecha commented on tests/functional/afr/heal/test_afr_self_heal_add_brick_rebalance.py
> +
okay

2021-08-03 17:24 UTC, nik-redhat commented
Yeah, it can be classified as nonDisruptive as it won't hamper the working of any other TC if ran in parallel.

2021-08-03 17:41 UTC, srijan-sivakumar commented
> Yeah, it can be classified as nonDisruptive as it won't hamper the working of any other TC if ran in parallel.

I think we must check this out once. The framework does have the logic but it just destroys the updated volume and recreates a new volume.

2021-08-03 17:44 UTC, nik-redhat commented
Ok, so now I remember why we chose the expansion and shrinking of the volumes to be disruptive. It was because of add-brick and remove-brick operation when run simultaneously gave issues from gluster's end.

2021-08-03 17:48 UTC, Sheetalpamecha commented
> Results for heal
Test nature : nonDisruptive
TestName : test_afr_self_heal_add_brick_rebalance
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:04:54       |      NA     |
|     arb     |     PASS    |        00:05:22       |      NA     |
|   dist-rep  |     PASS    |        00:04:55       |      NA     |
|   dist-arb  |     PASS    |        00:04:53       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   0   |
|         Non Disruptive Tests         |   3   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   12  |
|            Tests Skipped             |   0   |
|             Total Tests              |   3   |
|   Disruptive Tests Pass Percentage   |   0   |
| Non Disruptive Tests Pass Percentage | 100.0 |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 12 minutes 37 seconds
✔ Tearing down successful.

2021-08-03 17:49 UTC, Sheetalpamecha commented
Correct it to Disruptive, and update with new results

2021-08-04 05:30 UTC, Sheetalpamecha commented
```Results for heal
Test nature : disruptive
TestName : test_afr_self_heal_add_brick_rebalance
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     arb     |     PASS    |        00:04:02       |      NA     |
|   dist-arb  |     PASS    |        00:02:00       |      NA     |
|     rep     |     PASS    |        00:04:04       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   3   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 14 minutes 52 seconds
✔ Tearing down successful.
```

2021-08-04 06:46 UTC, nik-redhat requested changes

2021-08-04 06:46 UTC, nik-redhat commented on tests/functional/afr/heal/test_afr_self_heal_add_brick_rebalance.py
> +                    raise Exception("Mismatch of arequal checksum")
This is comparing the variable's value to itself, and it needs to be updated.
You can check out the logic on how to do the comparison in the case of `collect_bricks_arequal` from this [PR](https://github.com/gluster/redant/pull/925/files#diff-ab5676db42df8886d5f2087c0cad3d222060e6b6e1e0fea59f7a2b135bb769b6R123-R135) line: 123-135

2021-08-04 10:10 UTC, Sheetalpamecha commented on tests/functional/afr/heal/test_afr_self_heal_add_brick_rebalance.py
> +                    raise Exception("Mismatch of arequal checksum")
Done

2021-08-04 10:25 UTC, nik-redhat approved these changes

2021-08-04 10:26 UTC, merged