Migrated TC test_default_granular_entry_heal
gluster/redant pull request #927
Opened 2021-08-04 11:05 UTC by nik-redhat

Migrated TC [test_default_granular_entry_heal](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_default_granular_entry_heal.py)

And, added the op `occurences_of_pattern_in_file`.

Updates: #292 
Signed-off-by: nik-redhat <nladha@redhat.com>

2021-08-04 11:42 UTC, nik-redhat commented
```
Results for afr
Test nature : disruptive
TestName : test_default_granular_entry_heal
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:02:29       |      NA     |
|   dist-rep  |     PASS    |        00:00:33       |      NA     |
|     arb     |     PASS    |        00:00:29       |      NA     |
|   dist-arb  |     PASS    |        00:00:35       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   4   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 04 minutes 21 seconds
✔ Tearing down successful.
```

2021-08-04 12:56 UTC, srijan-sivakumar requested changes

2021-08-04 12:56 UTC, srijan-sivakumar commented on common/ops/support_ops/io_ops.py
> +    def occurences_of_pattern_in_file(self, node: str, search_pattern: str,
Can't we re-use or re-struturize the function `check_if_pattern_in_file` to be called inside this function or maybe with a simple flag, instead of returning 0 for pattern present in file, if the flag is enabled we can return the number of occurrences. I feel we are just duplicating the logic in this new function `occurences_of_pattern_in_file`.

2021-08-04 12:56 UTC, srijan-sivakumar commented on tests/functional/afr/test_default_granular_entry_heal.py
> +    def _add_dir_path_to_brick_list(brick_list):
Just curious, any specific reason for keeping this method as static method ?

2021-08-04 12:56 UTC, srijan-sivakumar commented on tests/functional/afr/test_default_granular_entry_heal.py
> +        if self.volume_type == "dist-rep" or self.volume_type == "dist-arb":
Seeing that we just execute the test for rep, arb, dist-rep and dist-arb, we can simply put this check as an else, as the previous if conditional already checks for rep and arb and the else part will cover for dist-rep and dist-arb.

2021-08-04 13:00 UTC, nik-redhat commented on tests/functional/afr/test_default_granular_entry_heal.py
> +    def _add_dir_path_to_brick_list(brick_list):
Not sure, I just kept it the same as the glusto TC. It doesn't make any difference if we don't make it static. What do you suggest?

2021-08-04 13:00 UTC, nik-redhat commented on tests/functional/afr/test_default_granular_entry_heal.py
> +        if self.volume_type == "dist-rep" or self.volume_type == "dist-arb":
Ack

2021-08-04 13:05 UTC, srijan-sivakumar commented on tests/functional/afr/test_default_granular_entry_heal.py
> +    def _add_dir_path_to_brick_list(brick_list):
Well, in python static functions don't get to use the class's context or the object's context, and most of the times they're used to execute some logic which is independent of object. Seeing the function logic, we are just operating over the parameters being passed and hence I don't see any harm in making it static, I think we should actually mark such methods as static consciously wherein the method just takes in some input parameters, operates over them and returns a response. We can prevent the class or objects' context coming into picture when the interpreter might push this method to the stack, because in case of normal methods and class methods, these functions get the object or class reference as the first parameter by default.

2021-08-04 13:13 UTC, nik-redhat commented on common/ops/support_ops/io_ops.py
> +    def occurences_of_pattern_in_file(self, node: str, search_pattern: str,
So you mean we should have only one function like `check_pattern_in_file` and use flags to do the counting as well? Or, have both but reuse the other one inside this one?

2021-08-04 13:23 UTC, srijan-sivakumar commented on common/ops/support_ops/io_ops.py
> +    def occurences_of_pattern_in_file(self, node: str, search_pattern: str,
I feel we can just go with the first method. Just use check_pattern_in_file and with the flag enabled, return the number of occurrences.

2021-08-04 13:32 UTC, nik-redhat commented on common/ops/support_ops/io_ops.py
> +    def occurences_of_pattern_in_file(self, node: str, search_pattern: str,
I think if we keep one function then there will be a lot of nested `if-else` which will necessarily make the code complex. Using the other function inside this function seems better to me.

2021-08-04 13:36 UTC, nik-redhat commented on common/ops/support_ops/io_ops.py
> +    def occurences_of_pattern_in_file(self, node: str, search_pattern: str,
Anyways, let me check and see how it goes, I will push the changes once done.

2021-08-04 13:52 UTC, srijan-sivakumar commented on common/ops/support_ops/io_ops.py
> +    def occurences_of_pattern_in_file(self, node: str, search_pattern: str,
Do check it out...and see which is better...

2021-08-04 15:20 UTC, nik-redhat commented on common/ops/support_ops/io_ops.py
> +    def occurences_of_pattern_in_file(self, node: str, search_pattern: str,
I have kept the new function and reused the other function due to issues with return value and its usage.

2021-08-04 15:22 UTC, nik-redhat commented
```
Results for afr
Test nature : disruptive
TestName : test_default_granular_entry_heal
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:00:35       |      NA     |
|   dist-rep  |     PASS    |        00:00:40       |      NA     |
|     arb     |     PASS    |        00:00:32       |      NA     |
|   dist-arb  |     PASS    |        00:00:39       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   4   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 02 minutes 42 seconds
✔ Tearing down successful.
```

2021-08-05 04:29 UTC, Sheetalpamecha approved these changes

2021-08-09 13:26 UTC, srijan-sivakumar approved these changes

2021-08-09 13:26 UTC, merged