Migrated TC tests/functional/afr/heal/test_heal_info_no_hang.py
gluster/redant pull request #953
Opened 2021-08-16 09:11 UTC by Sheetalpamecha

[Migrated TC tests/functional/afr/heal/test_heal_info_no_hang.py](https://github.com/gluster/glusto-tests/blob/35f1b97a8ecee852b2543e87ceb2ebbe9cf4f6ca/tests/functional/afr/heal/test_heal_info_no_hang.py)

Updates: #292
Signed-off-by: Sheetal Pamecha spamecha@redhat.com

2021-08-16 09:14 UTC, Sheetalpamecha commented
```
Results for heal
Test nature : disruptive
TestName : test_heal_info_no_hang
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   dist-rep  |     PASS    |        00:01:33       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 02 minutes 04 seconds
✔ Tearing down successful.
```

2021-08-17 04:32 UTC, srijan-sivakumar requested changes

2021-08-17 04:32 UTC, srijan-sivakumar commented on tests/functional/afr/heal/test_heal_info_no_hang.py
> +        1. Start kernel untar on the mount
Nit: as we are not performing kernel untar and are just doing simple I/O but in higher volume, the steps can be modified to reflect that.

2021-08-17 05:14 UTC, Sheetalpamecha commented on tests/functional/afr/heal/test_heal_info_no_hang.py
> +        1. Start kernel untar on the mount
done

2021-08-17 05:17 UTC, srijan-sivakumar approved these changes

2021-08-17 05:28 UTC, merged