[Test] Migrating test_uss_snao_activate_deactivate
gluster/redant pull request #955
Opened 2021-08-16 15:59 UTC by srijan-sivakumar

Migrating [test_uss_snap_activate_deactivate.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_uss_snap_active_deactive.py)

Updates: #292 

Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

2021-08-16 16:21 UTC, srijan-sivakumar commented
```console
(redant-demo) [root@rhsdev-virt05 redant]# python3 core/redant_main.py -c ../rconfig.yml -t tests/functional/snapshot/test_uss_snap_active_deactive.py -ll D
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

✔ Param Handling Success.
✔ Test List built
✔ Log dir creation successful.
✔ Environment setup successful.
✔ Running test case : test_uss_snap_active_deactive-rep
✔ test_uss_snap_active_deactive-rep Succeeded
✔ Running test case : test_uss_snap_active_deactive-dist
✔ test_uss_snap_active_deactive-dist Succeeded
✔ Running test case : test_uss_snap_active_deactive-disp
✔ test_uss_snap_active_deactive-disp Succeeded
✔ Running test case : test_uss_snap_active_deactive-dist-rep
✔ test_uss_snap_active_deactive-dist-rep Succeeded
✔ Running test case : test_uss_snap_active_deactive-dist-disp
✔ test_uss_snap_active_deactive-dist-disp Succeeded
Results for snapshot
Test nature : disruptive
TestName : test_uss_snap_active_deactive
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:01:51       |      NA     |
|     dist    |     PASS    |        00:02:28       |      NA     |
|     disp    |     PASS    |        00:02:50       |      NA     |
|   dist-rep  |     PASS    |        00:03:07       |      NA     |
|  dist-disp  |     PASS    |        00:03:26       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   5   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 14 minutes 02 seconds
✔ Tearing down successful.
```

2021-08-17 05:29 UTC, nik-redhat requested changes

2021-08-17 05:29 UTC, nik-redhat commented on common/ops/support_ops/io_ops.py
> +            excep (bool): Whether to bypass the exception handling in
We are not using this flag to bypass the exception handling in abstract ops in this function. A different flag could be used or none could be used and the exception can be raised directly by the caller depending upon the return value.

2021-08-17 05:37 UTC, srijan-sivakumar commented on common/ops/support_ops/io_ops.py
> +            excep (bool): Whether to bypass the exception handling in
We need to have a flag as we don't want this op fn to raise an Exception. I'll change the description of the flag ( as exception handling is being prevented in this fn and not in abstract ops ) and maybe just its name but the purpose is to bypass the exception in the ops function.

2021-08-17 05:43 UTC, nik-redhat commented on common/ops/support_ops/io_ops.py
> +            excep (bool): Whether to bypass the exception handling in
I didn't get you...... There is an exception being raised at line: 683 in case `_rc` is "False" but you are saying we don't want to raise an exception in this op?
Also, shouldn't there be a default value for this flag?

2021-08-17 05:53 UTC, srijan-sivakumar commented on common/ops/support_ops/io_ops.py
> +            excep (bool): Whether to bypass the exception handling in
What I mean to say is that in this one particular test case, we don't want the exception to be thrown in case of `_rc` to be `False`. As per the default value, it needs to be `True` as this op in normal conditions should handle the exception in case of `_rc` is False.

2021-09-10 16:38 UTC, nik-redhat commented
Closing wrt PR #1064

2021-09-10 16:38 UTC, closed without merging