Migrated TC test_multiple_clients_dd_on_same_file_default
gluster/redant pull request #961
Opened 2021-08-17 12:05 UTC by nik-redhat

Migrated TC [test_multiple_clients_dd_on_same_file_default](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_multiple_clients_dd_on_same_file_default.py)

Updates: #292
Signed-off-by: nik-redhat <nladha@redhat.com>

2021-08-17 15:12 UTC, nik-redhat commented
```

Results for afr
Test nature : disruptive
TestName : test_multiple_clients_dd_on_same_file_default
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:04:08       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 08 minutes 29 seconds
✔ Tearing down successful.
```

2021-08-18 04:11 UTC, Sheetalpamecha requested changes

2021-08-18 04:11 UTC, Sheetalpamecha commented on tests/functional/afr/test_multiple_clients_dd_on_same_file_default.py
> +        brick_list = data_brick_list
This should be done for arbiter volumes only. We should put a check here for volume-type

2021-08-18 04:11 UTC, srijan-sivakumar approved these changes

2021-08-18 05:26 UTC, nik-redhat commented on tests/functional/afr/test_multiple_clients_dd_on_same_file_default.py
> +        brick_list = data_brick_list
It won't affect the time consumption a lot since it's only a 3 iteration loop. Hence, didn't add a check.

2021-08-18 05:36 UTC, Sheetalpamecha commented on tests/functional/afr/test_multiple_clients_dd_on_same_file_default.py
> +        brick_list = data_brick_list
yeah but a single check is better than a nested 3 iteration loop.

2021-08-18 05:40 UTC, nik-redhat commented on tests/functional/afr/test_multiple_clients_dd_on_same_file_default.py
> +        brick_list = data_brick_list
Done.

2021-08-18 05:47 UTC, Sheetalpamecha approved these changes

2021-08-18 06:00 UTC, merged