Migrated TC tests/functional/afr/heal/test_metadata_split_brain_resolution.py
gluster/redant pull request #962
Opened 2021-08-17 12:22 UTC by Sheetalpamecha

[Migrated TC tests/functional/afr/heal/test_metadata_split_brain_resolution.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/heal/test_metadata_split_brain_resolution.py)

Updates: #292
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

2021-08-17 12:43 UTC, Sheetalpamecha commented
```
✔ test_metadata_split_brain_resolution-rep Succeeded
Results for heal
Test nature : disruptive
TestName : test_metadata_split_brain_resolution
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:01:35       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 02 minutes 06 seconds
✔ Tearing down successful.
```

2021-08-17 13:40 UTC, nik-redhat requested changes

2021-08-17 13:40 UTC, nik-redhat commented on tests/functional/afr/heal/test_metadata_split_brain_resolution.py
> +                                  self.server_list[0])
We can use the `multi_option` flag here so that all the options are set in one command.

2021-08-17 13:40 UTC, nik-redhat commented on tests/functional/afr/heal/test_metadata_split_brain_resolution.py
> +    def run_test(self, redant):
Could you please add the test steps here?
Even if it is not present in the glusto TC (just to keep things consistent)

2021-08-18 04:47 UTC, Sheetalpamecha commented on tests/functional/afr/heal/test_metadata_split_brain_resolution.py
> +                                  self.server_list[0])
Done

2021-08-18 04:47 UTC, Sheetalpamecha commented on tests/functional/afr/heal/test_metadata_split_brain_resolution.py
> +    def run_test(self, redant):
done

2021-08-18 04:47 UTC, Sheetalpamecha commented
```
✔ test_metadata_split_brain_resolution-rep Succeeded
Results for heal
Test nature : disruptive
TestName : test_metadata_split_brain_resolution
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:01:41       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 02 minutes 13 seconds
✔ Tearing down successful.
```

2021-08-18 05:35 UTC, nik-redhat commented on tests/functional/afr/heal/test_metadata_split_brain_resolution.py
> +        cmd = (f"find {self.mountpoint} | xargs stat")
the `get_mounts_stat` op can be used for this.

2021-08-18 06:07 UTC, Sheetalpamecha commented on tests/functional/afr/heal/test_metadata_split_brain_resolution.py
> +        cmd = (f"find {self.mountpoint} | xargs stat")
ohh yes, I checked this function. This does get stat of all mount points. but to use this func, we will need to call another func get_mnt_pts_dict_in_list. As we have a single mt point we can avoid this and can get the desired result with the current code too.

2021-08-18 06:16 UTC, nik-redhat commented on tests/functional/afr/heal/test_metadata_split_brain_resolution.py
> +        cmd = (f"find {self.mountpoint} | xargs stat")
Using this op is better because `find` accompanied with `xargs` can give a lot of misleading results and has some other concerns as well. For reference, check out this [discussion](https://unix.stackexchange.com/questions/321697/why-is-looping-over-finds-output-bad-practice).
As far as calling that function is concerned, we don't need to do that. Instead, we can simply declare our own dict like:
```
self.mounts = {
    "client": self.client_list[0],
    "mountpath": self.mountpoint
}
```
And this can be passed to the op. Just make one update to the op, and that is to check for `if not isinstance(mounts, list)` and convert to list if not already a list (as done in other ops).

2021-08-19 05:10 UTC, Sheetalpamecha commented on tests/functional/afr/heal/test_metadata_split_brain_resolution.py
> +        cmd = (f"find {self.mountpoint} | xargs stat")
done

2021-08-19 05:10 UTC, Sheetalpamecha commented
```
✔ Running test case : test_metadata_split_brain_resolution-rep
✔ test_metadata_split_brain_resolution-rep Succeeded
Results for heal
Test nature : disruptive
TestName : test_metadata_split_brain_resolution
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:01:42       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   1   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 02 minutes 14 seconds
✔ Tearing down successful.
```

2021-08-19 05:11 UTC, nik-redhat approved these changes

2021-08-19 05:16 UTC, merged