Added flag for clearing ggluster logs
gluster/redant pull request #981
Opened 2021-08-24 07:39 UTC by nik-redhat

## Description:

Added a flag to allow clearing of old glusterfs logs at the time of environment setup. By default, the value is set to True.
Fixes: #980 

Signed-off-by: nik-redhat <nladha@redhat.com>

2021-08-24 07:46 UTC, nik-redhat commented
```
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

usage: redant_main.py [-h] -c CONFIG_FILE -t TEST_DIR [-l LOG_DIR] [-ll LOG_LEVEL] [-cc CONCUR_COUNT] [-xls EXCEL_SHEET] [--show-backtrace] [--clear-old-logs CLEAR_LOGS]

Redant test framework main script.

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG_FILE, --config CONFIG_FILE
                        Config file(s) to read.
  -t TEST_DIR, --test-dir TEST_DIR
                        The test directory where TC(s) exist
  -l LOG_DIR, --log-dir LOG_DIR
                        The directory wherein log will be stored.
  -ll LOG_LEVEL, --log-level LOG_LEVEL
                        The log level. Default log level is Info
  -cc CONCUR_COUNT, --concurrency-count CONCUR_COUNT
                        Number of concurrent test runs. Default is 2.
  -xls EXCEL_SHEET, --excel-sheet EXCEL_SHEET
                        Spreadsheet for result. Default value is NULL
  --show-backtrace      Show full backtrace on error
  --clear-old-logs CLEAR_LOGS
                        Clear glusterfs logs directory during environment setup
```

2021-08-24 08:07 UTC, nik-redhat commented
```
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

usage: redant_main.py [-h] -c CONFIG_FILE -t TEST_DIR [-l LOG_DIR] [-ll LOG_LEVEL] [-cc CONCUR_COUNT] [-xls EXCEL_SHEET] [--show-backtrace] [--clear-old-logs CLEAR_LOGS]

Redant test framework main script.

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG_FILE, --config CONFIG_FILE
                        Config file(s) to read.
  -t TEST_DIR, --test-dir TEST_DIR
                        The test directory where TC(s) exist
  -l LOG_DIR, --log-dir LOG_DIR
                        The directory wherein log will be stored.
  -ll LOG_LEVEL, --log-level LOG_LEVEL
                        The log level. Default log level is Info
  -cc CONCUR_COUNT, --concurrency-count CONCUR_COUNT
                        Number of concurrent test runs. Default is 2.
  -xls EXCEL_SHEET, --excel-sheet EXCEL_SHEET
                        Spreadsheet for result. Default value is NULL
  --show-backtrace      Show full backtrace on error
  --clear-old-logs CLEAR_LOGS
                        Clear glusterfs logs directory during environment setup. Default is Yes
```

2021-08-24 08:46 UTC, srijan-sivakumar commented on core/redant_main.py
> +    parser.add_argument("--clear-old-logs",
just a suggestion, I think we can keep one more name...say '-cold' along with '--clear-old-logs'

2021-08-24 08:49 UTC, nik-redhat commented on core/redant_main.py
> +    parser.add_argument("--clear-old-logs",
Yeah, we can have that as well :sweat_smile:

2021-08-24 08:54 UTC, nik-redhat commented
```
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

usage: redant_main.py [-h] -c CONFIG_FILE -t TEST_DIR [-l LOG_DIR] [-ll LOG_LEVEL] [-cc CONCUR_COUNT] [-xls EXCEL_SHEET] [--show-backtrace]
                      [-cold CLEAR_LOGS]

Redant test framework main script.

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG_FILE, --config CONFIG_FILE
                        Config file(s) to read.
  -t TEST_DIR, --test-dir TEST_DIR
                        The test directory where TC(s) exist
  -l LOG_DIR, --log-dir LOG_DIR
                        The directory wherein log will be stored.
  -ll LOG_LEVEL, --log-level LOG_LEVEL
                        The log level. Default log level is Info
  -cc CONCUR_COUNT, --concurrency-count CONCUR_COUNT
                        Number of concurrent test runs. Default is 2.
  -xls EXCEL_SHEET, --excel-sheet EXCEL_SHEET
                        Spreadsheet for result. Default value is NULL
  --show-backtrace      Show full backtrace on error
  -cold CLEAR_LOGS, --clear-old-logs CLEAR_LOGS
                        Clear glusterfs logs directory during environment setup. Default is Yes
```

2021-08-24 10:52 UTC, srijan-sivakumar requested changes

2021-08-24 10:52 UTC, srijan-sivakumar commented on core/redant_main.py
> +    parser.add_argument("-cold", "--clear-old-logs",
Instead of having a YES and NO system here, I think we can simply use the format used for `xls`. Therein the default value is None. There's no need to provide a value for the flag, the flag when provided is enough for giving indication to the program to delete the logs.

2021-08-24 11:26 UTC, nik-redhat commented on core/redant_main.py
> +    parser.add_argument("-cold", "--clear-old-logs",
Actually, not the XLS format but the `show-backtrace` format?
Also, the difference here is that when we provide the flag we don't want the logs to be cleared and by default, the logs will be cleared. For that, I guess we might need to tweak the flag name a bit, any suggestion for the name?

2021-08-24 11:27 UTC, nik-redhat commented on core/redant_main.py
> +    parser.add_argument("-cold", "--clear-old-logs",
How about `keep-old-logs` , `kold` ?

2021-08-25 05:48 UTC, srijan-sivakumar commented on core/redant_main.py
> +    parser.add_argument("-cold", "--clear-old-logs",
cool. We can follow the way of show-backtrace. I think kold sounds good :p

2021-08-25 05:49 UTC, srijan-sivakumar commented
@nik-redhat can you attach the usage once ? Just for validation.

2021-08-25 06:01 UTC, nik-redhat commented
```
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

usage: redant_main.py [-h] -c CONFIG_FILE -t TEST_DIR [-l LOG_DIR] [-ll LOG_LEVEL] [-cc CONCUR_COUNT] [-xls EXCEL_SHEET] [--show-backtrace] [-kold]

Redant test framework main script.

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG_FILE, --config CONFIG_FILE
                        Config file(s) to read.
  -t TEST_DIR, --test-dir TEST_DIR
                        The test directory where TC(s) exist
  -l LOG_DIR, --log-dir LOG_DIR
                        The directory wherein log will be stored.
  -ll LOG_LEVEL, --log-level LOG_LEVEL
                        The log level. Default log level is Info
  -cc CONCUR_COUNT, --concurrency-count CONCUR_COUNT
                        Number of concurrent test runs. Default is 2.
  -xls EXCEL_SHEET, --excel-sheet EXCEL_SHEET
                        Spreadsheet for result. Default value is NULL
  --show-backtrace      Show full backtrace on error
  -kold, --keep-old-logs
                        Don't clear the old glusterfs logs directory during environment setup
```

2021-08-25 06:02 UTC, nik-redhat commented
> @nik-redhat can you attach the usage once ? Just for validation.

Done

2021-08-25 06:22 UTC, Sheetalpamecha approved these changes

2021-08-25 06:33 UTC, srijan-sivakumar approved these changes

2021-08-25 06:34 UTC, merged