Migrated TC test_self_heal_with_meta_data_entry_and_files_removed.py
gluster/redant pull request #985
Opened 2021-08-24 12:51 UTC by Sheetalpamecha

[Migrated TC test_self_heal_with_meta_data_entry_and_files_removed.py](https://github.com/gluster/glusto-tests/blob/35f1b97a8ecee852b2543e87ceb2ebbe9cf4f6ca/tests/functional/afr/heal/test_self_heal_with_meta_data_entry_and_files_removed.py)

Updates:#292
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

2021-08-24 12:51 UTC, Sheetalpamecha commented
```
✔ Running test case : test_self_heal_with_meta_data_entry_and_files_removed-dist-rep
✔ test_self_heal_with_meta_data_entry_and_files_removed-dist-rep Succeeded
✔ Running test case : test_self_heal_with_meta_data_entry_and_files_removed-rep
✔ test_self_heal_with_meta_data_entry_and_files_removed-rep Succeeded
Results for heal
Test nature : disruptive
TestName : test_self_heal_with_meta_data_entry_and_files_removed
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   dist-rep  |     PASS    |        00:20:51       |      NA     |
|     rep     |     PASS    |        00:21:02       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   2   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 42 minutes 22 seconds
✔ Tearing down successful.
```

2021-08-25 05:25 UTC, nik-redhat requested changes

2021-08-25 05:25 UTC, nik-redhat commented on tests/functional/afr/heal/test_self_heal_with_meta_data_entry_and_files_removed.py
> +        if self.user_group_created:
This should be under the try block

2021-08-25 05:25 UTC, nik-redhat commented on tests/functional/afr/heal/test_self_heal_with_meta_data_entry_and_files_removed.py
> +        self.user_group_created = False
This should be defined at the beginning of the `run_test` function, as before reaching this definition the TC might fail

2021-08-25 07:39 UTC, Sheetalpamecha commented on tests/functional/afr/heal/test_self_heal_with_meta_data_entry_and_files_removed.py
> +        self.user_group_created = False
Done

2021-08-25 07:39 UTC, Sheetalpamecha commented on tests/functional/afr/heal/test_self_heal_with_meta_data_entry_and_files_removed.py
> +        if self.user_group_created:
Done

2021-08-25 07:42 UTC, nik-redhat approved these changes

2021-08-25 07:42 UTC, merged