Migrated TC test_self_heal_with_link_files.py
gluster/redant pull request #986
Opened 2021-08-25 05:29 UTC by Sheetalpamecha

[Migrated TC test_self_heal_with_link_files.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/heal/test_self_heal_with_link_files.py)
    
Updates: #292
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>

2021-08-25 07:17 UTC, Sheetalpamecha commented
```
Results for heal
Test nature : disruptive
TestName : test_self_heal_with_link_files
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time Taken (hh:mm:ss) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   dist-rep  |     PASS    |        00:05:37       |      NA     |
|     rep     |     PASS    |        00:04:55       |      NA     |
+-------------+-------------+-----------------------+-------------+
+--------------------------------------+-------+
|               Category               | Count |
+--------------------------------------+-------+
|           Disruptive Tests           |   1   |
|         Non Disruptive Tests         |   0   |
|       Disruptive Tests Skipped       |   0   |
|     Non Disruptive Tests Skipped     |   0   |
|              Tests Ran               |   2   |
|            Tests Skipped             |   0   |
|             Total Tests              |   1   |
|   Disruptive Tests Pass Percentage   | 100.0 |
| Non Disruptive Tests Pass Percentage |   0   |
|        Total Pass Percentage         | 100.0 |
+--------------------------------------+-------+
Total Time Taken : 00 hours 11 minutes 02 seconds
✔ Tearing down successful.

```

2021-08-25 08:17 UTC, nik-redhat requested changes

2021-08-25 08:17 UTC, nik-redhat commented on tests/functional/afr/heal/test_self_heal_with_link_files.py
> +                  "of=dir.$i/file.$j bs=1k count=$j; done; done")
I think can go under the `if` part ?

2021-08-25 08:17 UTC, nik-redhat commented on tests/functional/afr/heal/test_self_heal_with_link_files.py
> +        if second_attempt:
And, after making the above change, we can simply use an else here.

2021-08-30 05:37 UTC, Sheetalpamecha commented on tests/functional/afr/heal/test_self_heal_with_link_files.py
> +                  "of=dir.$i/file.$j bs=1k count=$j; done; done")
Yes

2021-08-30 05:37 UTC, Sheetalpamecha commented on tests/functional/afr/heal/test_self_heal_with_link_files.py
> +        if second_attempt:
Done

2021-08-30 05:47 UTC, nik-redhat approved these changes

2021-08-30 05:48 UTC, merged